name: CI
on:
  push:
    branches:
      - '*'
jobs:
  quality:
    name: Quality
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Create NPMRC
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "@kamaal111:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Install node modules
        run: |
          yarn

      - name: Lint
        run: |
          yarn lint

  deploy:
    name: Deploy
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    needs: [quality]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Create NPMRC
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "@kamaal111:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Install node modules
        run: |
          yarn

      - name: Build project
        run: |
          node "scripts/metadata.js"

          yarn build
          npx next export
          mkdir out/.well-known
          touch out/.nojekyll

      - name: Make CNAME
        run: |
          node scripts/deploy/cname.js

      - name: Make app site association
        run: |
          node scripts/deploy/appleAppSiteAssociation.js

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: out
