name: CI
on:
  push:
    branches:
      - '*'
      - 'feature/*'
jobs:
  deploy:
    name: Deploy
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'

      - name: Build project
        run: |
          yarn build:production

      - name: Deploy 🚀
        run: |
          yarn
          yarn deploy || exit 1
