name: CI
on:
  push:
    branches:
      - develop
      - 'release/**'
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Run deploy script
        run: |
          git config user.name "kamaal111" && git config user.email "kamaal.f1@gmail.com"
          npm run deploy
